apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: books-cmd
  name: books-cmd
  namespace: fenix-poc-v1
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: books-cmd
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: books-cmd
    spec:
      containers:
      - image: 910440518126.dkr.ecr.eu-central-1.amazonaws.com/fenix-poc/bookstore/book-cmd:v1
        name: books-cmd
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
