version: "3"

volumes:
  axon-es:

networks:
  axon:
    external: true

services:
  axonsrv:
    image: axoniq/axonserver
    container_name: axonsrv
    ports:
      - 8024:8024
      - 8124:8124
    networks:
      - axon

#  swagger-editor:
#    image: swaggerapi/swagger-editor
#    container_name: swagger-editor
#    ports:
#      - 7000:8080
#
#  swagger-ui:
#    image: swaggerapi/swagger-ui
#    container_name: swagger-ui
#    ports:
#      - 7001:8080
