version: "3"

networks:
  axon:
    external: true

services:
  apigw:
    build: ./_be-api-gw
    image: bookstore/apigw:latest
    container_name: apigw
    ports:
      - 8000:8080
    networks:
      - axon

  books-cmd:
    build:
      context: ./books
      dockerfile: Dockerfile-cmd
    image: bookstore/books-cmd:latest
    container_name: books-cmd
    ports:
      - 8001:8080
    networks:
      - axon

  books-query:
    build:
      context: ./books
      dockerfile: Dockerfile-query
    image: bookstore/books-query:latest
    container_name: books-query
    ports:
      - 8002:8080
    networks:
      - axon
