version: "3"

networks:
  axon:
    external: true

services:
  apigw:
    build: ./_be-api-gw
    image: 910440518126.dkr.ecr.eu-central-1.amazonaws.com/fenix-poc/bookstore/apigw:v1
    container_name: apigw
    ports:
      - 8000:8080
    networks:
      - axon

  books-cmd:
    build:
      context: ./books
      dockerfile: Dockerfile-cmd
    image: 910440518126.dkr.ecr.eu-central-1.amazonaws.com/fenix-poc/bookstore/book-cmd:v1
    container_name: books-cmd
    ports:
      - 8001:8080
    networks:
      - axon

  books-query:
    build:
      context: ./books
      dockerfile: Dockerfile-query
    image: 910440518126.dkr.ecr.eu-central-1.amazonaws.com/fenix-poc/bookstore/book-query:v1
    container_name: books-query
    ports:
      - 8002:8080
    networks:
      - axon
