version: "3"

networks:
  axon:
    external: true

services:
  books-cmd:
    build:
      context: .
      dockerfile: Dockerfile-cmd
    image: osaou/books-cmd:latest
    container_name: books-cmd
    ports:
      - 8001:8080
    networks:
      - axon

  books-query:
    build:
      context: .
      dockerfile: Dockerfile-query
    image: osaou/books-query:latest
    container_name: books-query
    ports:
      - 8002:8080
    networks:
      - axon
